### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by harperjohn** [BlazingSaddlesSolutions/TimeKeeper#11]
When I first started looking into Blazor, I looked into Autofac because I thought that I had to use an external library... Then I found out that MS DI had matured and (apparently) was quite usable... so I put Autofac on the back burner, and mostly out of my mind. 

But then the "3 scopes" options of MS DI started to feel a bit limiting... especially since "scooped" seems to default/degenerate to "singleton" for Blazor server apps...

I feel the the MS DI is not "keeping up" with Blazor or maybe it is just too simple/rigid in general.

I could go either way MS DI or Autofac DI... but in either case, I think we should really understand/define our use of DI

I think DI is very useful and effective, but I feel that most people use it in a "boilerplate" / "automatic-reflex" way which can lessen (if not completely undermine) its use.

**Comment by AnkurSheel** [comment]
My 2 cents - I am happy to use MS DI especially as it's a learning project. 
It's also easy to migrate from MS DI to Autofac etc if you start hitting running into problems at scale. You don't hit problems with Singletons in DI till you start serving a large volume of requests. 

Also,  avoids the need to learn another library
