### ISSUE TITLE
TimeKeeperServer exception error

### ISSUE THREAD

**Issue by harperjohn** [BlazingSaddlesSolutions/TimeKeeper#38]
I got the project to build.

I am running a "multiple startup project" run with TimeKeeper.Api, TimeKeeperClient, and TimeKeeperServer.

TimeKeeperClient seems to run fine

TimeKeeperServer throws the exception shown in the attachment. 

[exceptionJohn.txt](https://github.com/BlazingSaddlesSolutions/TimeKeeper/files/6480742/exceptionJohn.txt)

**Comment by DotNetDublin** [comment]
Do you get the same error if you set it to run only TimeKeeper.Api and TimeKeeperServer?

**Comment by harperjohn** [comment]
Yes - Timekeeper.Api and TimeKeeperServer (without TimeKeeperClient) causes the same error.

**Comment by DotNetDublin** [comment]
Okay, I note the below line in the error log

```
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:44331)
```

I received this error before and it related to the API refusing the connection. I got passed it so I would maybe search for references to localhost across the application and check whether the ports match those seen when you launch the application?

**Comment by harperjohn** [comment]
so... I ran it with just the client... and the Swagger UI tool came up, and it looks like the API is just not working. I imagine that the server crashes right away because it must try to use the API on its own... and I imagine that the client does not crash because it does not use the api.. or maybe because it is wasm it is more insulated... not sure.

Are there some key/critical points where we can add exception handling to the API so that we can catch/find the location of the problem?

**Comment by DotNetDublin** [comment]
Let me know if the problem persists when using the [refit-spike](https://github.com/BlazingSaddlesSolutions/TimeKeeper/tree/refit-spike) branch. See comment from [Jon](https://github.com/BlazingSaddlesSolutions/TimeKeeper/issues/42#issuecomment-841836394) here.

**Comment by DotNetDublin** [comment]
I've updated the main branch to include the launch settings Jon applied to refit-spike

The application worked for me setting the startup projects as

* API and Server
* API and Client
* API and Server and Client

If you pull the latest changes from the main branch it should work for you now but let us know if the problem persists.

**Comment by DotNetDublin** [comment]
Closing issue as @harperjohn has confirmed issue is no longer found in the current version.

See [comment](https://github.com/BlazingSaddlesSolutions/TimeKeeper/discussions/50#discussioncomment-757811) in discussion #50
