### ISSUE TITLE
Create a version using vertical slices

### ISSUE THREAD

**Issue by jonhilt** [BlazingSaddlesSolutions/TimeKeeper#41]
I think at this early stage we've a really useful opportunity to throw some ideas around regarding project architecture.

With that in mind I'm working on a quick port of the project to a version which employs vertical slices, and is more aligned with the kind of project structure I've found myself using in recent times.

I'll make sure to share notes on what I've implemented (and why) and what problems I think it addresses! 👍

**Comment by jonhilt** [comment]
I've created a couple of branches but the main one now is the refit-spike branch.

I need to to jump off and spend a bit of time with the family (eek!) but I've started exploring a few different ideas in there and will endeavour to write a bit about the various things I'm throwing against the wall (to see what sticks) when I find a spare half hour or so 😄

**Comment by DotNetDublin** [comment]
Is it worth me looking at the refit-spike branch or should I hold off for now?

**Comment by jonhilt** [comment]
Thanks for waiting for me @DotNetDublin! I tried to distil my thoughts here:

https://github.com/BlazingSaddlesSolutions/TimeKeeper/discussions/47

**Comment by jonhilt** [comment]
This branch #48 has now been merged into #main
